CREATE TABLE users(
    id UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    name VARCHAR(255) NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE phones(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    userId UUID NOT NULL,
    number BIGINT NULL,
    citycode INT NULL,
    countrycode VARCHAR(2) NULL,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

